#!/bin/bash
# JWT MECHANISM QUICK START

echo "================================"
echo "🔐 BARBER JWT MECHANISM DEMO"
echo "================================"
echo ""

echo "📝 Kroki uruchomienia:"
echo ""
echo "1️⃣  Przejdź do katalogu projektu:"
echo "    cd c:\Users\kondz1o\Desktop\Barber\Barber"
echo ""

echo "2️⃣  Uruchom aplikację Spring Boot:"
echo "    mvnw spring-boot:run"
echo ""
echo "    (lub w PowerShell: .\mvnw.cmd spring-boot:run)"
echo ""
echo "    ✅ Czekaj aż zobaczysz: 'Tomcat started on port(s): 8080'"
echo ""

echo "3️⃣  Otwórz VS Code (jeśli jeszcze nie uruchomiony)"
echo "    - Otwórz plik: demo.http"
echo ""

echo "4️⃣  Wykonuj żądania HTTP po kolei:"
echo "    - Kliknij 'Send Request' obok każdego żądania"
echo "    - Zacznij od kroku 1️⃣ (Rejestracja)"
echo "    - Idź po kolei do kroku 3️⃣1️⃣"
echo ""

echo "5️⃣  Obserwuj wyniki:"
echo "    - Tokeny będą wyświetlane w response'ie"
echo "    - Role będą pokazane w JSON'ie"
echo "    - Błędy będą wyświetlane dla niepoprawnych żądań"
echo ""

echo "================================"
echo "📌 WAŻNE PLIKI"
echo "================================"
echo ""
echo "📄 demo.http"
echo "   └─ 31 żądań HTTP do testowania JWT"
echo ""
echo "📄 JWT_MECHANISM_DEMO.md"
echo "   └─ Pełna dokumentacja (architektura + kod)"
echo ""
echo "💻 Klasy Java:"
echo "   - JwtUtils.java          (generowanie/weryfikacja tokenów)"
echo "   - AuthTokenFilter.java   (filtrowanie na każde żądanie)"
echo "   - AuthRestController.java (logowanie/rejestracja)"
echo "   - TokenDemoController.java (endpointy demonstracyjne)"
echo "   - SecurityConfig.java    (konfiguracja bezpieczeństwa)"
echo ""

echo "================================"
echo "🔑 TESTUJESZ CO?"
echo "================================"
echo ""
echo "✅ Generowanie JWT tokenów z rolami"
echo "✅ Weryfikacja tokenów na każde żądanie"
echo "✅ Wyciągnięcie roli z tokenu"
echo "✅ Kontrola dostępu na podstawie ról"
echo "✅ Endpointy demonstracyjne (user-info, has-role, etc.)"
echo "✅ Testy błędów (brak tokenu, niepoprawny token)"
echo ""

echo "================================"
echo "📊 ROLE W SYSTEMIE"
echo "================================"
echo ""
echo "👨‍💼 KLIENT"
echo "   - Dostęp do: /client/**, /api/reservations"
echo ""
echo "💇 BARBER"
echo "   - Dostęp do: /barber/**, /api/tasks, /api/reservations"
echo ""
echo "👨‍💻 ADMIN"
echo "   - Dostęp do: wszystko"
echo ""

echo "================================"
echo "✨ HAPPY TESTING!"
echo "================================"
